config/routes.rb
require 'sidekiq/web'
Sidekiq::Web.set :session_secret, Rails.application.credentials[:secret_key_base]

Rails.application.routes.draw do
  resources :notes
  resources :issue_groups
  resources :issues
  resources :screenshots, only: [:edit, :update, :destroy]
  resources :reports
  resources :clients
  resources :issue_templates
  devise_for :users, controllers: { registrations: "registrations", sessions: "sessions"}
  mount ActionCable.server => '/cable'
  root to: redirect(path: '/scans')

  get '/scans' => 'pages#scans'

  get '/issue_templates/create_from_issue/:issue_id' => 'issue_templates#create_from_issue', as: :issue_template_create_from_issue
  post '/issue_templates/search' => 'issue_templates#search', as: :issue_templates_search
  post '/issue_templates/search_add' => 'issue_templates#search_add', as: :issue_templates_search_add

  post '/reports/change_parent' => 'reports#change_parent', as: :change_parent
  match '/reports/:id/export_docx' => 'reports#export_docx', as: :export_odt, via: [:get, :post]
  match '/reports/:id/export_xlsx' => 'reports#export_xlsx', as: :export_xlsx, via: [:get, :post]
  match '/reports/:id/export_verinice' => 'reports#export_verinice', as: :export_verinice, via: [:get, :post]

  # index ever used, ever?
  resources :groups, only: %i[create new]

  post 'groups/group' => 'groups#group', as: :single_group_html

  post 'groups/create_form' => 'groups#create_form'

  post 'groups/copy_form' => 'groups#copy_form'
  post 'groups/copy' => 'groups#copy'

  post 'groups/move_form' => 'groups#move_form'
  post 'groups/move' => 'groups#move'

  post 'groups/export_form' => 'groups#export_form'
  post 'groups/export' => 'groups#export'

  post 'groups/delete_form' => 'groups#delete_form'
  post 'groups/delete' => 'groups#delete'

  post 'groups/delete_clients_form' => 'groups#delete_clients_form'
  post 'groups/delete_clients' => 'groups#delete_clients'

  post 'groups/scan_form' => 'groups#scan_form'

  get 'groups/refresh' => 'groups#refresh', as: :group_refresh
  get 'groups/group_list' => 'groups#group_list', as: :group_list

  get '/issues/:id/update_template' => 'issues#update_template', as: :update_template
  get '/issues/:id/new_template' => 'issues#new_template', as: :new_template
  get '/issues/:id/confirm_update_template' => 'issues#confirm_update_template', as: :confirm_update_template
  get '/issues/:id/confirm_create_template' => 'issues#confirm_create_template', as: :confirm_create_template

  get '/groups' => 'groups#index'
  get '/pages/settings' => 'pages#settings', as: :global_settings

  get '/images' => 'images#index', as: :images
  get '/images/scan_all' => 'images#scan_all', as: :images_scan_all
  get '/images/scan_all_overwrite' => 'images#scan_all_overwrite', as: :images_scan_all_overwrite

  get '/clients/search/form' => 'clients#search_form', as: :global_search_view
  post '/clients/global_search' => 'clients#global_search', as: :global_search
  post '/clients/archive' => 'clients#archive', as: :clients_archive
  post '/clients/unarchive' => 'clients#unarchive', as: :clients_unarchive
  get '/clients/:id/new_issue_form' => 'clients#new_issue_form', as: :clients_new_issue_form
  get '/clients/:id/link_issue_form' => 'clients#link_issue_form', as: :clients_link_issue_form
  get '/clients/:id/link_issue/:issue' => 'clients#link_issue', as: :clients_link_issue
  get '/clients/:id/unlink_issue/:issue' => 'clients#unlink_issue', as: :clients_unlink_issue

  post 'setting/update_user_settings' => 'setting#update_user_settings', as: :update_user_settings
  post 'settings/update' => 'settings#update', as: :update_settings

  post 'scans/create' => 'scans#create'
  post 'scans/upload' => 'scans#upload'
  post 'scans/download' => 'scans#download', as: :download_scan
  authenticate :user do
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/models/issue.rb
class Issue < ReportPart
  belongs_to :reportable, polymorphic: true

  def self.create_from_template(issue_group, issue_template)
    Issue.create(
      reportable: issue_group,
      title: issue_template.title,
      description: issue_template.description,
      rating: issue_template.rating,
      recommendation: issue_template.recommendation,
      severity: issue_template.severity,
      uuid: issue_template.uuid
    )
  end

  def color
    case severity
    when 0
      'green'
    when 1
      'blue'
    when 2
      'orange'
    when 3
      'red'
    when 4
      'purple'
    else
      'grey'
    end
  end

  def color_hex
    case severity
    when 0
      '#3fb079;'
    when 1
      '#0b5394;'
    when 2
      '#b45f06;'
    when 3
      '#990000;'
    when 4
      '#9900ff;'
    else
      '#999999;'
    end
  end
end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  before_action :set_issue, only: [:show, :edit, :update, :destroy, :update_template, :confirm_update_template, :new_template, :confirm_create_template]
  before_action :set_mysql_client, only: [:confirm_update_template, :update_template, :new_template]

  # GET /issues
  # GET /issues.json
  def index
    @issues = Issue.all
  end

  # GET /issues/1
  # GET /issues/1.json
  def show
  end

  def confirm_create_template
    @issue_template_remote = nil
    respond_to do |format|
      format.html { redirect_to root_path }
      format.js { render 'issues/confirm_update_template' }
    end
  end

  # GET /issues/1/confirm_update_template/
  def confirm_update_template
    uid = @mysql_client.escape(@issue.uuid.to_s)
    begin
      rt = @mysql_client.query("SELECT * FROM issue_templates WHERE id=#{uid}")
      if rt.size == 1
        @issue_template_remote = rt.first
      else
        @issue_template_remote = nil
      end
    rescue => exception
      #respond_with_notify(exception.to_s, "alert")
      respond_with_notify("something went wrong with the mysql query: 90842", "alert")
      # redirect_back(fallback_location: root_path, alert: "something went wrong with the mysql connection2")
    end
  end

  def new_template
    title = @mysql_client.escape(@issue.title)
    description = @mysql_client.escape(@issue.description)
    rating = @mysql_client.escape(@issue.rating)
    recommendation = @mysql_client.escape(@issue.recommendation)
    severity = @mysql_client.escape(@issue.severity.to_s)
    begin
      @mysql_client.query("INSERT INTO issue_templates (title, description, rating, recommendation, severity) VALUES ('#{title}','#{description}','#{rating}','#{recommendation}','#{severity}')")
      
      # get the ID from the current insert.
      # the function `last_id` use the last inserted id from the current session, so it's thread save. 
      # https://stackoverflow.com/questions/8161211/get-affected-row-in-ruby-after-doing-an-insert-in-mysql
      @issue.uuid = @mysql_client.last_id
      @issue.save

      # create new local cached issue template (overwrite if uuid already exist)
      it = IssueTemplate.find_or_create_by(uuid: @issue.uuid)
      it.title = @issue.title
      it.description = @issue.description
      it.rating = @issue.rating
      it.recommendation = @issue.recommendation
      it.severity = @issue.severity
      it.save
    rescue => exception
      respond_with_notify("something went wrong with the mysql connection: 9080231", "alert")
    end
    respond_with_refresh("Issue was successfully synced to the remote database.", "success")
  end

  # GET /issues/1/update_template/
  def update_template
    uid = @mysql_client.escape(@issue.uuid.to_s)
    title = @mysql_client.escape(@issue.title)
    description = @mysql_client.escape(@issue.description)
    rating = @mysql_client.escape(@issue.rating)
    recommendation = @mysql_client.escape(@issue.recommendation)
    severity = @mysql_client.escape(@issue.severity.to_s)
    begin
      @mysql_client.query("UPDATE issue_templates SET title = '#{title}', description = '#{description}', rating = '#{rating}', recommendation = '#{recommendation}', severity = '#{severity}' WHERE id=#{uid}")
      
      # update local cached issue template (create if uuid didn't exist)
      it = IssueTemplate.find_or_create_by(uuid: @issue.uuid)
      it.title = @issue.title
      it.description = @issue.description
      it.rating = @issue.rating
      it.recommendation = @issue.recommendation
      it.severity = @issue.severity
      it.save
    rescue => exception
      respond_with_notify("something went wrong with the mysql connection: 2090203", "alert")
    end
    respond_with_refresh("Issue was successfully synced to the remote database.", "success")
  end

  # GET /issues/new
  def new
    @issue = Issue.new
    @issue_templates = IssueTemplate.all
  end

  # GET /issues/1/edit
  def edit
    @report_parts = ReportPart.where(type: "IssueGroup")
    case current_user.settings.where(name: 'report_mode').first_or_create.value
    when "presentation"
      respond_to do |format|
        format.html { redirect_to root_path }
        format.js { render 'issues/present' }
      end
    else
    end
  end

  # POST /issues
  # POST /issues.json
  def create
    respond_to do |format|
      current_report = Report.first_or_create
      unless current_report.report_parts.empty?
        lastIssueGroup = current_report.report_parts.last
        if lastIssueGroup.type == "IssueGroup"
          if params.key?(:issue_template) && (IssueTemplate.exists? params[:issue_template])
            issue_clone = Issue.create_from_template(lastIssueGroup, IssueTemplate.find(params[:issue_template]))
            if (params.key?(:client) && client = Client.find_by_id(params[:client]))
              issue_clone.clients << client
            end
            format.html { redirect_to reports_path, notice: 'Issue was successfully created from template.' }
          else
            empty_issue_template = IssueTemplate.new
            empty_issue_template.title = "New blank issue"
            empty_issue_template.description = ""
            empty_issue_template.rating = ""
            empty_issue_template.recommendation = ""
            empty_issue_template.severity = -1
            empty_issue_template.uuid = 0

            Issue.create_from_template(lastIssueGroup, empty_issue_template)
            format.html { redirect_to reports_path, notice: 'New issue was created. Consider syncing it later.' }
          end
        else
          format.html { redirect_to reports_path, alert: 'Last report part is no issue group' }
        end
      else
        format.html { redirect_to reports_path, alert: 'No issue group found in current report. Please create a new one first.' }
      end
    end
  end

  # PATCH/PUT /issues/1
  # PATCH/PUT /issues/1.json
  def update
    if params[:issue][:screenshot].present?
      screenshot = @issue.screenshots.create
      screenshot.description = params[:issue][:screenshot][:description]
      screenshot.save
      screenshot.image.attach(params[:issue][:screenshot][:image])
    end
    if @issue.update(issue_params)
      respond_with_refresh("Issue was successfully updated.", "success")
    else
      respond_with_notify(@issue.errors, "alert")
    end
  end

  # DELETE /issues/1
  # DELETE /issues/1.json
  def destroy
    @issue.clients.delete_all
    @issue.screenshots.delete_all
    @issue.destroy
    respond_with_refresh("Issue was successfully destroyed.", "success")
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_issue
      unless @issue = Issue.find_by_id(params[:id])
        respond_with_notify("Value not found in DB", "alert")
      end
    end

    def set_mysql_client
      begin
        @mysql_client = Mysql2::Client.new(JSON.parse(current_user.settings.where(name: 'mysql_connection').first_or_create.value))
      rescue => exception
        respond_with_notify(exception, "alert")
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def issue_params
      params.require(:issue).permit(:title, :severity, :description, :customtargets, :rating, :recommendation, :type, :index)
    end

    def screenshot_params
      params.require(:issue).require(:screenshot).permit(:image, :description, :order)
    end

    def respond_with_refresh(message = 'Unknown error', type = 'alert', issue = 0)
      @report_parts = ReportPart.where(type: "IssueGroup")
      respond_to do |format|
        format.html { redirect_to root_path }
        format.js { render 'issues/refresh', locals: { message: message, type: type } }
      end
    end

    def respond_with_notify(message = 'Unknown error', type = 'alert')
      respond_to do |format|
        format.html { redirect_to root_path }
        format.js { render 'pages/notify', locals: { message: message, type: type } }
      end
    end
end

app/helpers/issues_helper.rb
module IssuesHelper
end

app/views/issues/_confirm_update_template_diff.html.erb
<style><%= Diffy::CSS %></style>
<div class="modal-content p-0">
    <div class="row orange lighten-4 pt-3 pb-2">
        <div class="col s12 center">
            <h3 class="orange-text text-darken-3">Apply changes to issue template</h3>
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col s12">
              <h5>Title</h5>
              <div class='well diff'>
                  <%= diff(@issue_template_remote['title'], @issue.title) %>
              </div>
            </div>
        </div>
        <div class="row">
            <div class="col s12">
              <h5>Description</h5>
              <div class='well diff'>
                  <%= diff(@issue_template_remote['description'], @issue.description) %>
              </div>
            </div>
        </div>
        <div class="row">
            <div class="col s12">
              <h5>Rating</h5>
              <div class='well diff'>
                  <%= diff(@issue_template_remote['rating'], @issue.rating) %>
              </div>
            </div>
        </div>
        <div class="row">
            <div class="col s12">
              <h5>Recommendation</h5>
              <div class='well diff'>
                  <%= diff(@issue_template_remote['recommendation'], @issue.recommendation) %>
              </div>
            </div>
        </div>
    </div>
</div>
<div class="modal-footer">
    <%= link_to update_template_path(@issue), remote: :true, class: "btn-flat green-text text-darken-2" do %>
        <i class="material-icons left">backup</i>Save to cloud
    <% end %>
</div>

app/views/issues/_confirm_update_template_new.html.erb
<div class="modal-content p-0">
    <div class="row green lighten-4 pt-3 pb-2">
        <div class="col s12 center">
            <h3 class="green-text text-darken-3">Create a new issue template</h3>
            <p class="green-text text-darken-3">Notice: The issue uuid was not found on the remote database or is empty</p>
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col s6">
                <h5>Title</h5>
                <p><%= @issue.title %></p>
            </div>
            <div class="col s6">
                <h5>Severity</h5>
                <i class="material-icons left <%= @issue.color %>-text text-darken-2">bug_report</i>
            </div>
        </div>
        <div class="row">
            <div class="col s6">
                <h5>Description</h5>
                <p><%= @issue.description %></p>
            </div>
            <div class="col s6">
                <h5>Rating</h5>
                <p><%= @issue.rating %></p>
            </div>
        </div>
        <div class="row">
            <div class="col s12">
                <h5>Recommendation</h5>
                <p><%= @issue.recommendation %></p>
            </div>
        </div>
    </div>
</div>
<div class="modal-footer">
    <%= link_to new_template_path(@issue), remote: :true, class: "btn-flat green-text text-darken-2" do %>
        <i class="material-icons left">backup</i>Save to cloud
    <% end %>
</div>

app/views/issues/_edit.html.erb
<%= simple_form_for :report, url: change_parent_path, remote: true do |f| %>
    <input type="hidden" value="<%= form_authenticity_token() %>" name="authenticity_token"/>
    <input type="hidden" value="<%= @issue.id %>" name="source"/>
    <div class="input-field col s3">
        <select name="new_parent" onchange="$(this).submit()">
            <% @report_parts.each do |report_part| %>
                <option <%= (report_part.id.equal? @issue.reportable.id) ? 'selected' : '' %> value="<%= report_part.id %>"><%= report_part.title %></option> 
            <% end %>
            <option value="0">Current report</option>
        </select>
        <label>New parent</label>
    </div>
<% end %>
<%= simple_form_for @issue, remote: true do |f| %>
    <%= f.input :title, required: true, wrapper_html: { class: 'col s5' } %>
    <%= f.input :severity, collection: [['information', '0'],['low', '1'], ['medium', '2'], ['high', '3'], ['critical', '4']], include_blank: false, wrapper_html: { class: 'col s2' } %>
    <%= f.input :index, wrapper_html: { class: 'col s1' } %>
    <div class="col s1 input-field">
        <button type="submit" class="btn right blue darken-2 btn-save"><i class="material-icons">save</i></button>
    </div>   

    <div class="row">
        <%= f.input :description, wrapper_html: { class: 'col s6' }, input_html: { class: 'editor'} %>
        <div class="col s6">
            <div class="row"></div> <!-- empty dirty row for padding =/ -->
            <div class="row">
                <div class="col s12 file-field input-field">
                    <div class="btn tooltipped" data-position="top" data-tooltip="To insert images from clipbloard just press STRG + V">
                        <span>new screenshot</span>
                        <input type="file" name="issue[screenshot][image]" id="issue_screenshot_image">
                    </div>
                    <div class="file-path-wrapper">
                        <input class="file-path validate" type="text" id="issue_screenshot_image_path">
                    </div>            
                </div>
            </div>
            <div class="row">
                <% @issue.screenshots.each do |screenshot| %>
                    <div class="col s3">
                        <%= image_tag url_for(screenshot.image), :class => "materialboxed tooltipped pb-05", width: '100%', data: { position: "top", tooltip: screenshot.description.nil? ? "No description yet" : screenshot.description } %>
                        <%= link_to edit_screenshot_path(screenshot), class: "btn-flat left grey lighten-3", remote: true do %>
                            <i class="material-icons orange-text text-darken-3">description</i>
                        <% end %>
                        <%= link_to screenshot, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn-flat right grey lighten-3", remote: true do %>
                            <i class="material-icons red-text text-darken-3">delete</i>
                        <% end %>
                    </div>
                <% end %>
            </div>
        </div> 
    </div>
    <div class="row">
        <%= f.input :customtargets, label: "Custom targets", wrapper_html: { class: 'col s6' } %>
        <div class="col s6">
            <div class="pb-05"><label class="text optional active">Linked clients</label><i class="material-icons tooltipped" data-position="bottom" data-delay="50" data-tooltip="Use group view in order to link clients with issues">info_outline</i></div>
            <% @issue.clients.each do |client| %>
              <div class="chip">
                <%= client.ip %><%= " (#{client.hostname})" unless client.hostname.nil? %>
                <%= link_to clients_unlink_issue_path(client, @issue),remote: true do %>
                    <i class="close red-text text-darken-2 material-icons">close</i>
                <% end %>
              </div>  
            <% end %>
        </div>
    </div>
    <div class="row">
        <%= f.input :rating, wrapper_html: { class: 'col s6' }, input_html: { class: 'editor'} %>
        <%= f.input :recommendation, wrapper_html: { class: 'col s6' }, input_html: { class: 'editor'} %>    
    </div>
<% end %>

app/views/issues/_form.html.erb
<%= simple_form_for(@issue) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :severity %>
    <%= f.input :description %>
    <%= f.input :customtargets %>
    <%= f.input :rating %>
    <%= f.input :recommendation %>
    <%= f.input :type %>
    <%= f.input :index %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/issues/_link.html.erb
<div class="container pt-2">
    <div class="row">
        <div class="col s12">
            <div class="pb-05"><label class="text optional active">Linked client</label></div>
            <div class="chip"><%= @client.ip %><%= " (#{@client.hostname})" unless @client.hostname.nil? %></div>
        </div>
    </div>
    <div class="row">
        <div class="col s12">
            <ul class="collection issue-template-collection">
                <% @issues.each do |issue| %>
                    <li class="collection-item issue-template-collection-item">
                        <i class="material-icons left <%= issue.color %>-text text-darken-2">bug_report</i><%= issue.title %>    
                        <%= link_to '<i class="material-icons green-text text-darken-3">link</i>'.html_safe, clients_link_issue_path(@client, issue), remote: "true", :class => "secondary-content tooltipped", data: { position: "bottom", tooltip: "Link client to that issue" } %>
                    </li>
                <% end %>   
            </ul> 
        </div>
    </div>    
</div>

app/views/issues/_new.html.erb
<div class="modal-content p-0">
    <div class="row blue lighten-5 pt-3 pb-2">
        <div class="col s12 center">
            <h3 class="blue-text text-darken-3">Create a new issue</h3>
        </div>
    </div>
    <div class="container">
        <div class="row issue_templates">
            <div class="col s12">
                <div class="row search-field">
                    <%= simple_form_for :search, url: issue_templates_search_add_path, method: "POST", remote: "true" do |f| %>
                        <div class="input-field col s6 ">
                            <% if @client %>
                                <input type="hidden" name="client" value="<%= @client.id %>">
                            <% end %>
                            <input placeholder="Type any issue title..." id="title" name="title" type="text" autofocus>
                            <label for="title">Search</label> 
                        </div>
                    <% end %>
                    <% if @client %>
                        <div class="col s6">
                            <div class="pb-05"><label class="text optional active">Linked client</label></div>
                            <div class="chip"><%= @client.ip %><%= " (#{@client.hostname})" unless @client.hostname.nil? %></div>
                        </div>
                    <% end %>
                </div>
                <ul class="collection issue-template-collection">
                    <% @issue_templates.each do |issue_template| %>
                        <li class="collection-item issue-template-collection-item">                        
                            <i class="material-icons left <%= issue_template.color %>-text text-darken-2">bug_report</i><%= issue_template.title %>
                            <%= simple_form_for @issue do |f| %>
                                <% if @client %>
                                    <input type="hidden" name="client" value="<%= @client.id %>">
                                <% end %>
                                <input type="hidden" name="issue_template" value="<%= issue_template.id %>">
                                <button type="submit" class="btn-flat grey lighten-2 green-text text-darken-1"> <i class="material-icons left">add</i>create issue</button>
                            <% end %>                        
                        </li>
                    <% end %>   
                </ul> 
            </div>
        </div>    
    </div>
</div>
<div class="modal-footer">
    <%= simple_form_for @issue do |f| %>
        <button type="submit" class="btn blue darken-3"> <i class="material-icons left">add</i>create blank issue</button>
    <% end %>
</div>

app/views/issues/_present.html.erb
<div class="row">
    <% @issue.screenshots.each do |screenshot| %>
        <div class="col s6">
            <%= image_tag url_for(screenshot.image), :class => "materialboxed pb-05", width: '100%' %>
            <span><%= screenshot.description %></span><br /><br />
        </div>
    <% end %>
</div>

app/views/issues/confirm_update_template.js.erb
<% if @issue_template_remote %>
    $("#medium-modal").modal('open');
    $("#medium-modal").html("<%= j(render('confirm_update_template_diff')) %>");
<% else %>
    $("#medium-modal").modal('open');
    $("#medium-modal").html("<%= j(render('confirm_update_template_new')) %>");
<% end %>

app/views/issues/edit.js.erb
$(".editor-container").html("<%= j render(partial: 'issues/edit') %>");
$(".editor").each(function(index, value) {
    ClassicEditor
    .create( value, {
        toolbar: {
            items: [
                'bold',
                'italic',
                'fontColor',
                'fontBackgroundColor',
                'codeBlock',
                'highlight',
                'fontFamily',
                'horizontalLine',
                'specialCharacters',
                'link',
                'undo',
                'redo'
            ]
        },
        language: 'de'				
    });
});
M.updateTextFields();
$(document).ready(function(){
    $('select').formSelect();
    $('.tooltipped').tooltip({delay: 50});
    $('.materialboxed').materialbox();
});

app/views/issues/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Issues</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Severity</th>
      <th>Description</th>
      <th>Customtargets</th>
      <th>Rating</th>
      <th>Recommendation</th>
      <th>Type</th>
      <th>Index</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @issues.each do |issue| %>
      <tr>
        <td><%= issue.title %></td>
        <td><%= issue.severity %></td>
        <td><%= issue.description %></td>
        <td><%= issue.customtargets %></td>
        <td><%= issue.rating %></td>
        <td><%= issue.recommendation %></td>
        <td><%= issue.type %></td>
        <td><%= issue.index %></td>
        <td><%= link_to 'Show', issue %></td>
        <td><%= link_to 'Edit', edit_issue_path(issue) %></td>
        <td><%= link_to 'Destroy', issue, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Issue', new_issue_path %>

app/views/issues/new.js.erb
$("#medium-modal").html("<%= j render(partial: 'issues/new') %>");
M.updateTextFields();
$("#medium-modal").modal('open');

app/views/issues/present.js.erb
$(".editor-container").html("<%= j render(partial: 'issues/present') %>");
$(document).ready(function(){
    $('.materialboxed').materialbox();
});
        

app/views/issues/refresh.js.erb
$('.material-tooltip').remove();
<% if @issue.present? && Issue.exists?(@issue.id) %>
    $(".editor-container").html("<%= j render(partial: 'issues/edit') %>");
<% else %>
    $(".editor-container").html("")
<% end %>

$("#report_tree").html("<%= j render(partial: 'report_parts/report_tree') %>");
$(".editor").each(function(index, value) {
    ClassicEditor
    .create( value, {
        toolbar: {
            items: [
                'bold',
                'italic',
                'fontColor',
                'fontBackgroundColor',
                'codeBlock',
                'highlight',
                'fontFamily',
                'horizontalLine',
                'specialCharacters',
                'link',
                'undo',
                'redo'
            ]
        },
        language: 'de'				
    });
});
M.updateTextFields();
$(document).ready(function(){
    $('select').formSelect();
    $('.tooltipped').tooltip({delay: 50});
    $('.materialboxed').materialbox();
});
$("#medium-modal").modal('close');
<%= render(:template => 'pages/notify', :handlers => [:erb], :formats => [:js], locals:{message: message, type: type}) %>

app/views/issues/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @issue.title %>
</p>

<p>
  <strong>Severity:</strong>
  <%= @issue.severity %>
</p>

<p>
  <strong>Description:</strong>
  <%= @issue.description %>
</p>

<p>
  <strong>Customtargets:</strong>
  <%= @issue.customtargets %>
</p>

<p>
  <strong>Rating:</strong>
  <%= @issue.rating %>
</p>

<p>
  <strong>Recommendation:</strong>
  <%= @issue.recommendation %>
</p>

<p>
  <strong>Type:</strong>
  <%= @issue.type %>
</p>

<p>
  <strong>Index:</strong>
  <%= @issue.index %>
</p>

<%= link_to 'Edit', edit_issue_path(@issue) %> |
<%= link_to 'Back', issues_path %>