config/routes.rb
require 'sidekiq/web'
Sidekiq::Web.set :session_secret, Rails.application.credentials[:secret_key_base]

Rails.application.routes.draw do
  resources :notes
  resources :issue_groups
  resources :issues
  resources :screenshots, only: [:edit, :update, :destroy]
  resources :reports
  resources :clients
  resources :issue_templates
  devise_for :users, controllers: { registrations: "registrations", sessions: "sessions"}
  mount ActionCable.server => '/cable'
  root to: redirect(path: '/scans')

  get '/scans' => 'pages#scans'

  get '/issue_templates/create_from_issue/:issue_id' => 'issue_templates#create_from_issue', as: :issue_template_create_from_issue
  post '/issue_templates/search' => 'issue_templates#search', as: :issue_templates_search
  post '/issue_templates/search_add' => 'issue_templates#search_add', as: :issue_templates_search_add

  post '/reports/change_parent' => 'reports#change_parent', as: :change_parent
  match '/reports/:id/export_docx' => 'reports#export_docx', as: :export_odt, via: [:get, :post]
  match '/reports/:id/export_xlsx' => 'reports#export_xlsx', as: :export_xlsx, via: [:get, :post]
  match '/reports/:id/export_verinice' => 'reports#export_verinice', as: :export_verinice, via: [:get, :post]

  # index ever used, ever?
  resources :groups, only: %i[create new]

  post 'groups/group' => 'groups#group', as: :single_group_html

  post 'groups/create_form' => 'groups#create_form'

  post 'groups/copy_form' => 'groups#copy_form'
  post 'groups/copy' => 'groups#copy'

  post 'groups/move_form' => 'groups#move_form'
  post 'groups/move' => 'groups#move'

  post 'groups/export_form' => 'groups#export_form'
  post 'groups/export' => 'groups#export'

  post 'groups/delete_form' => 'groups#delete_form'
  post 'groups/delete' => 'groups#delete'

  post 'groups/delete_clients_form' => 'groups#delete_clients_form'
  post 'groups/delete_clients' => 'groups#delete_clients'

  post 'groups/scan_form' => 'groups#scan_form'

  get 'groups/refresh' => 'groups#refresh', as: :group_refresh
  get 'groups/group_list' => 'groups#group_list', as: :group_list

  get '/issues/:id/update_template' => 'issues#update_template', as: :update_template
  get '/issues/:id/new_template' => 'issues#new_template', as: :new_template
  get '/issues/:id/confirm_update_template' => 'issues#confirm_update_template', as: :confirm_update_template
  get '/issues/:id/confirm_create_template' => 'issues#confirm_create_template', as: :confirm_create_template

  get '/groups' => 'groups#index'
  get '/pages/settings' => 'pages#settings', as: :global_settings

  get '/images' => 'images#index', as: :images
  get '/images/scan_all' => 'images#scan_all', as: :images_scan_all
  get '/images/scan_all_overwrite' => 'images#scan_all_overwrite', as: :images_scan_all_overwrite

  get '/clients/search/form' => 'clients#search_form', as: :global_search_view
  post '/clients/global_search' => 'clients#global_search', as: :global_search
  post '/clients/archive' => 'clients#archive', as: :clients_archive
  post '/clients/unarchive' => 'clients#unarchive', as: :clients_unarchive
  get '/clients/:id/new_issue_form' => 'clients#new_issue_form', as: :clients_new_issue_form
  get '/clients/:id/link_issue_form' => 'clients#link_issue_form', as: :clients_link_issue_form
  get '/clients/:id/link_issue/:issue' => 'clients#link_issue', as: :clients_link_issue
  get '/clients/:id/unlink_issue/:issue' => 'clients#unlink_issue', as: :clients_unlink_issue

  post 'setting/update_user_settings' => 'setting#update_user_settings', as: :update_user_settings
  post 'settings/update' => 'settings#update', as: :update_settings

  post 'scans/create' => 'scans#create'
  post 'scans/upload' => 'scans#upload'
  post 'scans/download' => 'scans#download', as: :download_scan
  authenticate :user do
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/models/group.rb
class Group < ApplicationRecord
  validates :name, presence: true
  has_and_belongs_to_many :clients, -> { distinct }
  
  def images
    clients.map{|c| c.images}.flatten.sort{|i| i.created_at}
  end
end

app/controllers/groups_controller.rb
# @restful_api 1.0
# Handle all things group related
class GroupsController < ApplicationController
  # @url /groups/new
  # @action GET
  #
  # renders :new, a form for group creation
  def new
    respond_to do |format|
      format.html { redirect_to root_path }
      format.js { render :new }
    end
  end

  # @url /pages/refresh
  # @action GET
  #
  # Refreshes group view
  def refresh
    respond_to do |format|
      format.html {}
      format.js { render 'groups/group_refresh', locals: { message: 'Group content has been refreshed', type: 'success', delete: '-2' } }
    end
  end

  # @url /pages/group_list
  # @action POST
  #
  # Render the sidebar in the group view
  def group_list
    respond_to do |format|
      format.html {}
      format.js { render 'groups/group_list' }
    end
  end

  # @url /groups
  # @action POST
  #
  # Creates a new group
  #
  # @required [String] :group[:name] Name of the new group
  # @optional [Integer] :source_group ID of the source group
  # @optional [Array<Integer>] :selected_clients IDs of selected clients
  # @optional [String] :search true/false, indicator if :selected_clients are a result of a search
  # @optional [String] :move true/false, indicator if :selected_clients should be moved to the new group
  def create
    name = params[:group][:name]
    selected_clients = params[:selected_clients] if params[:selected_clients].present?
    search = ActiveModel::Type::Boolean.new.cast params[:search]
    source_group = search || params[:source_group].blank? ? nil : Group.find(params[:source_group])
    destination_group = Group.new
    destination_group.name = name.blank? ? 'Unknown' : name
    destination_group.icon = '<i class="fa ' + params[:group][:icon] + '"></i>'
    destination_group.mod = true

    affected_group = "-2"
    
    render(:create_custom) && return unless destination_group.save # warn instead?
    message = "New empty group '#{destination_group.name}' created"
    respond_with_refresh(message, "-2,-2", "-2") && return unless selected_clients.present?

    if params[:move].present? && params[:move].casecmp('true').zero?
      if search
        tmp_array = []
        selected_clients.each { |client| Client.find(client).groups.each { |group| tmp_array << group.id}}
        affected_group = tmp_array.uniq.join(",")
      else
        affected_group = source_group.id
      end
      move_do(selected_clients, destination_group, source_group, search)
    else
      selected_clients.each { |selected| destination_group.clients << Client.find(selected) }
    end

    destination_group.save

    message = "New group '#{destination_group.name}' with #{selected_clients.length} client(s) saved."
    respond_with_refresh(message, "#{affected_group},-2", "-2")
  end

  # @url /groups/create_form
  # @action POST
  #
  # Renders a form for group creation, providing clients
  def create_form
    prepare_form(:create_custom)
  end

  # @url /groups/move_form
  # @action POST
  #
  # Renders a form for moving clients
  def move_form
    prepare_form(:move)
  end

  # @url /groups/move
  # @action POST
  #
  # Moves clients to a group
  #
  # @required [String] :destination_group target group ID
  # @required [Integer] :source_group ID of the source group
  # @required [Array<Integer>] :selected_clients IDs of selected clients
  # @optional [String] :search true/false, indicator if :selected_clients are a result of a search
  def move
    search = ActiveModel::Type::Boolean.new.cast params[:search]
    destination_group = Group.find(params[:destination_group])

    search ? source_group = "-2" : source_group = Group.find(params[:source_group])
    edited_groups = move_do(params[:selected_clients], destination_group, source_group, search)
    edited_groups << destination_group.id
    
    message = "Moved #{params[:selected_clients].length} client(s) to group '#{destination_group.name}'"
    respond_with_refresh(message, "#{edited_groups.join(',')}", "-2")
  end

  def move_do(selected_clients, destination_group, source_group, search)
    edited_groups = Array.new
    selected_clients.each do |selected|
      client = Client.find(selected)
      destination_group.clients << client
      next unless destination_group.save
      if search
        client.groups.each do |group|
          group.clients.delete client unless group == destination_group
          edited_groups << group.id
        end
      else
        source_group.clients.delete client
        edited_groups << source_group.id
      end
    end
    return edited_groups
  end

  # @url /groups/copy_form
  # @action POST
  #
  # Renders a form for moving clients
  def copy_form
    prepare_form(:copy)
  end

  # @url /groups/group
  # @action POST
  #
  # Render a single group html datatable
  def group
    respond_to do |format|
      format.html {}
      format.js { render 'groups/group', locals: { group_id: params[:group_id] } }
    end
  end

  # @url /groups/copy
  # @action POST
  #
  # Copies clients to a group
  #
  # @required [String] :destination_group target group ID
  # @required [Array<Integer>] :selected_clients IDs of selected clients
  def copy
    destination_group = Group.find(params[:destination_group])

    params[:selected_clients].each { |selected| destination_group.clients << Client.find(selected) }

    message = "Copied #{params[:selected_clients].length} client(s) to group '#{destination_group.name}'"
    respond_with_refresh(message, "#{destination_group.id},-2", "-2")
  end

  # @url /groups/delete_clients_form
  # @action POST
  #
  # Renders a form for deleting clients
  def delete_clients_form
    prepare_form(:delete_clients)
  end

  # Renders a form for deleting clients
  def delete_form
    if params.key?(:source_group)
      if sg = Group.find(params[:source_group])
        locals = { source_group: sg, clients: sg.clients.where(archived: false) }
        respond_root_path_js(:delete_group, locals)
      else
        respond_with_notify("Group can not be found in database.")
      end
    else
      respond_with_notify
    end
  end

  # @url /groups/delete
  # @action POST
  #
  # Delete a group
  #
  # @required [String] :source_group ID of group to delete
  def delete
    source_group = Group.find(params[:source_group])

    source_group.clients.where(archived: false).each { |client| client.destroy if client.groups.length == 1 }
    message = "Deleted group '#{source_group.name}'"
    source_group.destroy

    respond_with_refresh(message, "#{source_group.id},-2", source_group.id)
  end

  # @url /groups/delete_clients
  # @action POST
  #
  # Deletes clients from a group (and the client itself if doesn't remain in any group or it was a search result)
  #
  # @required [String] :source_group ID of group to delete
  # @required [Array<Integer>] :selected_clients IDs of selected clients
  # @optional [String] :search true/false, indicator if :selected_clients are a result of a search
  def delete_clients
    edited_groups = Array.new
    search = ActiveModel::Type::Boolean.new.cast params[:search]

    search ? source_group = "-2" : source_group = Group.find(params[:source_group])
    selected_clients = params[:selected_clients]

    if search
      selected_clients.each do |selected|
        client = Client.find(selected)
        client.groups.each do |group|
          group.clients.delete(client)
          edited_groups << group.id
        end
        client.destroy
      end
      message = "Deleted #{selected_clients.length} client(s)."
    else
      selected_clients.each do |selected|
        client = Client.find(selected)
        source_group.clients.delete(client)
        client.destroy if client.groups.empty?
      end
      edited_groups << source_group.id
      message = "Deleted #{selected_clients.length} client(s) from group '#{source_group.name}'"
    end

    respond_with_refresh(message, "#{edited_groups.join(',')}", "-2")
  end

  def scan_form
    clients = Client.find(params[:clients]) if params.key?(:clients)
    if clients.blank?
      respond_with_notify
    else
      locals = { clients: clients }
      respond_root_path_js(:scan, locals)
    end
  end

  # @url /groups/export_form
  # @action POST
  #
  # Renders a form to export clients
  def export_form
    clients = Client.find(params[:clients]) if params.key?(:clients)

    if clients.nil? || clients.empty?
      respond_with_notify
    else
      locals = { clients: clients }
      respond_root_path_js(:export, locals)
    end
  end

  # @url /groups/export
  # @action POST
  #
  # Exports selected clients' IPs as a .yml - file
  #
  # @required [String] :group[:file_name] desired file_name
  # @required [Array<Integer>] :selected_clients IDs of selected clients
  def export
    file_name = (params[:group][:file_name].present? ? params[:group][:file_name] : 'exported_clients')
    clients = Client.where(id: params[:selected_clients]) if params[:selected_clients].present?
    if file_name && clients.present?
      file_name << '.txt' unless file_name =~ /.+\.(yml|yaml|txt)$/
      if file_name =~ /.+\.(yml|yaml)$/
        exceptions = %w[id created_at updated_at icon client_id]
        data = clients.left_outer_joins(:outputs, :ports).distinct.map do |c|
          ary = [c.attributes.except(*exceptions)]
          ary  << { 'ports' => c.ports.map { |p| p.attributes.except(*exceptions) } }
          ary  << { 'outputs' => c.outputs.map { |o| o.attributes.except(*exceptions) } }
        end
        send_data YAML.dump(data), filename: file_name, type: 'application/yaml'
      else
        data = clients.map(&:ip).join("\n")
        send_data data, filename: file_name, type: 'text/plain'
      end
    else
      respond_with_notify('That didn\'t work.', 'alert')
    end
  end

  private

  def respond_with_refresh(message, mod_gids, delete, type = 'notice')
    if current_user.settings.find_by_name('global_notify').value.include? "true"

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_copy.html.erb
<style>
  .iconsholder {
    box-sizing: unset;
  }
  .howl-iconpicker-close {
    width: 260px;
  }
  .srchicons {
    text-align: center !important;
  }
  .howl-iconpicker {
    background: #fff;
  }
  .selectedicon {
    background: #1976D2!important;
    border-color: #1976D2!important;
    color: #fff;
  }
</style>
<%= simple_form_for :group, url: groups_copy_path, remote: true do |f| %>
  <div class="modal-content">
    <a href="#" class="modal-action modal-close red-text text-darken-2 right btn-flat"><i class="material-icons">close</i></a>
    <div class="modal-header" style="border-bottom: 1px solid rgba(0, 0, 0, 0.1); padding-bottom: 20px; margin-bottom: 50px;">
      <h5 class="center-align">Copy selected clients to </h5>
    </div>
    <div class="row">
      <div class="col s6">
        <div class="input-field">
          <input disabled value="<%= source_group.name %>" id="disabled" type="text" class="validate" autofocus>
          <label for="disabled">Source Group</label>
          <input type="hidden" name="source_group" value="<%= source_group.id %>">
        </div>
      </div>
      <div class="input-field col s6">
        <select id="destination_group" name="destination_group">
          <option disabled selected>Choose your option</option>
          <%= options_from_collection_for_select(Group.where.not(id: source_group.id).order(mod: :desc, name: :asc), :id, :name) %>
        </select>
        <label>Select target group</label>
      </div>
    </div>
    <div class="row center-align" >
      <div class="col s12" style="margin-bottom: 13px;">
        <label>Selected Clients</label>
      </div>
      <div class="col s12">
        <% clients.each do | temp_client | %>
            <div class="chip"><%= temp_client.ip %></div>
            <input type="hidden" name="selected_clients[]" value="<%= temp_client.id %>" />
        <% end %>
      </div>
    </div>
  </div>
  <div class="modal-footer">
    <%= f.button :submit, 'Copy', :class => 'modal-action disabled', :id => 'submit-copy' %>
  </div>
<% end %>

<script>
    $('#destination_group').on('change', function(){ $('#submit-copy').removeClass('disabled'); });
</script>

app/views/groups/_delete_clients.html.erb
<style>
  .iconsholder {
    box-sizing: unset;
  }
  .howl-iconpicker-close {
    width: 260px;
  }
  .srchicons {
    text-align: center !important;
  }
  .howl-iconpicker {
    background: #fff;
  }
  .selectedicon {
    background: #1976D2!important;
    border-color: #1976D2!important;
    color: #fff;
  }
</style>
<%= simple_form_for :group, url: groups_delete_clients_path, remote: true do |f| %>
  <div class="modal-content">
    <a href="#" class="modal-action modal-close red-text text-darken-2 right btn-flat"><i class="material-icons">close</i></a>
    <div class="modal-header" style="border-bottom: 1px solid rgba(0, 0, 0, 0.1); padding-bottom: 20px; margin-bottom: 50px;">
      <h5 class="center-align">Delete selected clients</h5>
      <input type="hidden" name="search" value="<%= search %>">
    </div>
    <% if search %>
      <div class="row">
        <div class="col s12 m12">
          <div class="card red darken-4">
            <div class="card-content white-text">
              <span class="card-title">Warning</span>
              <p>This task will remove the selected client(s) from all groups and delete it from the database irreversible.</p>
            </div>
          </div>
        </div>
      </div>
    <% end %>
    <div class="row">
      <div class="col s12">
        <div class="input-field">
          <input disabled value="<%= source_group.name %>" id="disabled" type="text" class="validate" autofocus>
          <label for="disabled">Source Group</label>
          <input type="hidden" name="source_group" value="<%= source_group.id %>">
        </div>
      </div>
    </div>
    <div class="row center-align">
      <div class="col s12" style="margin-bottom: 13px;">
        <label>Selected Clients</label>
      </div>
      <div class="col s12">
        <% clients.each do | temp_client | %>
            <div class="chip"><%= temp_client.ip %></div>
            <input type="hidden" name="selected_clients[]" value="<%= temp_client.id %>" />
        <% end %>
      </div>
    </div>
  </div>
  <div class="modal-footer">
    <%= f.button :submit, 'Delete', :class => 'modal-action red darken-4' %>
  </div>
<% end %>

app/views/groups/index.html.erb
<style>
  #single_group_view {
    padding-top: 10px;
    position: fixed;
    overflow-y: auto;
    max-height: calc(100vh - 140px);
    min-height: calc(100vh - 64px);
  }
  #single_host_view {
    padding-top: 10px;
    position: fixed;
    overflow-y: auto;
    max-height: calc(100vh - 140px);
    min-height: calc(100vh - 64px);
  }
  .hidden {
    display: none;
  }
  #single_host_view_card {
    min-height: calc(100vh - 8em);
  }
  .btn-small {
    height: 28px;
    line-height: 28px;
    padding: 0 1.2rem;
  }
  .btn-small i {
    font-size: 1rem;
  }
  #wide-modal {
    width: 90% !important;
  }
  #medium-modal {
    width: 50% !important;
    z-index: 10000000 !important;
  }
  #generic-modal {
    z-index: 10000000 !important;  
  }
  .ui-selected{
    background: #edf4fd;
  }
  .ui-selecting{
    background: #edf4fd;
  }
  .table-header-groups {
    height: unset !important;
    display: grid !important;
  }
  .collapsible {
      box-shadow: none !important;
      border: none !important;
  }
</style>
<div class="groups-page">
  <div class="row">
    <div class="col s2" id="group_list">
      <%= render partial: "group_list" %>
    </div>
    <div class="col s5 offset-s2" id="single_group_view">
      <div class="selected-group"></div>
      <div class="row" id="group-placeholder">
        <div class="col s12 m12">
          <div class="card">
            <div class="card-content">
              <span class="card-title">No group selected</span>
              <a class="btn-floating btn-large halfway-fab red group_add_float"><i class="material-icons">group_add</i></a>
              <p>Please select a group or create a new one.</p>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="col s5 offset-s7" id="single_host_view">
      <div class="row">
        <div class="col s12 m12">
          <div class="card">
            <div class="card-content" id="single_host_view_card">
              <div id="hostview">
                <span class="card-title">Single Host View</span>
                <p>Please select a client to view the details.</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- Modal (generic) -->
<div id="generic-modal" class="modal modal-fixed-footer">
  <div id="modal-content">
  </div>
</div>

<!-- Modal (medium) -->
<div id="medium-modal" class="modal modal-fixed-footer">
  <div id="medium-modal-content">
  </div>
</div>

<!-- Modal (wide) -->
<div id="wide-modal" class="modal modal-fixed-footer">
  <div id="wide-modal-content">
  </div>
</div>

<div class="fixed-action-btn toolbar direction-top no-autoinit">
  <a class="btn-floating btn-large blue darken-3"><i class="material-icons">menu</i></a>
  <ul>
    <li><a href="#" class="tooltipped group_add_float" data-position="top" data-delay="50" data-tooltip="Add a group"><i class="material-icons">group_add</i></a></li>
    <li><a href="#" class="tooltipped search_float" data-position="top" data-delay="50" data-tooltip="Global search"><i class="material-icons">search</i></a></li>
  </ul>
</div>

<script>
    // Display group on click (sidebar)
    $(document).on("click", '.group-collection-item', function() {
        $(".loader").show();
        $("#group-placeholder").addClass("hidden");
        var id = this.getAttribute("gid");

        $(".group-collection-item").each(function( index ) {
          $(this).find(".fa").removeClass("blue-text text-darken-2");
        });
         $(this).find(".fa").addClass("blue-text text-darken-2");

        $.ajax({
            url: "<%= single_group_html_path %>",
            dataType : "script",
            cache: true,
            method: "post",
            data: {
                group_id: id
            }
        });
        $(this).blur();
    });

    // Datatable Search toogle with more than one datatables
    $(document).on("click", '.grp_search-toggle', function() {
        if ($(this).parents(".table-header").siblings(".dataTables_wrapper").find(".hiddensearch").css('display') == 'none')
            $(this).parents(".table-header").siblings(".dataTables_wrapper").find(".hiddensearch").slideDown();
        else
            $(this).parents(".table-header").siblings(".dataTables_wrapper").find(".hiddensearch").slideUp();

        $(this).blur();
    });

    // close Group Box
    $(document).on("click", '.grp_close', function() {
        var id = $('.selected-group').attr('gid');
        $(this).blur();
        $("#box_" + id).fadeOut(400, function() {
            $("#box_" + id).remove();
            $("#box_" + id).promise().done(function(){
                $("#group-placeholder").removeClass("hidden");
            });
        });
    });

    // update group content
    $(document).on("click", '.grp_update', function() {
        var id = $('.selected-group').attr('gid');
         $('.grp_update').tooltip('destroy');
         $.ajax({
            url: "<%= single_group_html_path %>",
            dataType : "script",
            cache: true,
            method: "post",
            data: {
                group_id: id
            }
        });
        $(this).blur();
    });

    // archive clients - group header
    $(document).on("click", '.grp_archive', function() {
      var id = $('.selected-group').attr('gid');
      var clients = new Array();
      $("#datatable-" +  id).find(".ui-selectable tr a").each(function() {
          if($(this).parents(".ui-selectee").hasClass("ui-selected")) {
              clients.push($(this).attr("id"));
          }
      });
      $.ajax({
          url: "<%= clients_archive_path %>",
          dataType : "script",
          cache: true,
          method: "post",
          data: {
              clients: clients,
              source_group: id
          }
      });
      $(this).blur();
    });

    // unarchive clients - group header
    $(document).on("click", '.grp_unarchive', function() {
      var id = $('.selected-group').attr('gid');
      var clients = new Array();
      $("#datatable-" +  id).find(".ui-selectable tr a").each(function() {
          if($(this).parents(".ui-selectee").hasClass("ui-selected")) {
              clients.push($(this).attr("id"));
          }
      });
      $.ajax({
          url: "<%= clients_unarchive_path %>",
          dataType : "script",
          cache: true,
          method: "post",
          data: {
              clients: clients,
              source_group: id
          }
      });
      $(this).blur();
    });

    // new group add - group header
    $(document).on("click", '.grp_new', function() {
        var search = false;
        var clients = new Array();
        var id = $('.selected-group').attr('gid');
        $("#datatable-" +  id).find(".ui-selectable tr a").each(function() {
            if($(this).parents(".ui-selectee").hasClass("ui-selected")) {
                clients.push($(this).attr("id"));
            }
        });

        // check if source group is search result
        if (id == "-1") { search = true; }

        if(clients.length == 0){
            $.ajax({
            url: "<%= new_group_path %>",
                dataType : "script",
                cache: true
            });
        } else {
            $.ajax({
                url: "<%= groups_create_form_path %>",
                dataType : "script",
                cache: true,
                method: "post",
                data: {
                    clients: clients,
                    source_group: id,
                    search: search
                }
            });
        }
        $(this).blur();
    });

    // copy selected clients - group header
    $(document).on("click", '.grp_copy', function() {
        var search = false;
        var clients = new Array();
        var id = $('.selected-group').attr('gid');
        $("#datatable-" +  id).find(".ui-selectable tr a").each(function() {
            if($(this).parents(".ui-selectee").hasClass("ui-selected")) {
                clients.push($(this).attr("id"));
            }
        });

        // check if source group is search result
        if (id == "-1") { search = true; }

        $.ajax({
            url: "<%= groups_copy_form_path %>",
            dataType : "script",
            cache: true,
            method: "post",
            data: {
                clients: clients,
                source_group: id,
                search: search
            }
        });

        $(this).blur();
    });

    // move selected clients - group header
    $(document).on("click", '.grp_move', function() {
        var search = false;
        var clients = new Array();
        var id = $('.selected-group').attr('gid');
        $("#datatable-" +  id).find(".ui-selectable tr a").each(function() {
            if($(this).parents(".ui-selectee").hasClass("ui-selected")) {
                clients.push($(this).attr("id"));
            }
        });

        // check if source group is search result
        if (id == "-1") { search = true; }

        $.ajax({
            url: "<%= groups_move_form_path %>",
            dataType : "script",
            cache: true,
            method: "post",
            data: {
                clients: clients,
                source_group: id,
                search: search
            }
        });

        $(this).blur();
    });

    // start new scan with selected clients - group header
    $(document).on("click", '.grp_scan', function() {
        var search = false;
        var clients = new Array();
        var id = $('.selected-group').attr('gid');
        $("#datatable-" +  id).find(".ui-selectable tr a").each(function() {
            if($(this).parents(".ui-selectee").hasClass("ui-selected")) {
                clients.push($(this).attr("id"));
            }
        });

        $.ajax({
            url: "<%= groups_scan_form_path %>",
            dataType : "script",
            cache: true,
            method: "post",
            data: {
                clients: clients,
                source_group: id,
                search: search
            }
        });

        $(this).blur();
    });

    // delete selected clients - group header
    $(document).on("click", '.grp_delete_clients', function() {
        var search = false;
        var clients = new Array();
        var id = $('.selected-group').attr('gid');
        $("#datatable-" +  id).find(".ui-selectable tr a").each(function() {
            if($(this).parents(".ui-selectee").hasClass("ui-selected")) {
                clients.push($(this).attr("id"));
            }
        });

        // check if source group is search result
        if (id == "-1") { search = true; }

        $.ajax({
            url: "<%= groups_delete_clients_form_path %>",
            dataType : "script",
            cache: true,
            method: "post",
            data: {
                clients: clients,
                source_group: id,
                search: search
            }
        });

        $(this).blur();
    });

    // delete group with all clients containing - group header
    $(document).on("click", '.grp_delete', function() {
        var id = $('.selected-group').attr('gid');
        $.ajax({
        url: "<%= groups_delete_form_path %>",
            dataType : "script",
            cache: true,
            method: "post",
            data: {
                source_group: id
            }
        });

        $(this).blur();
    });

    // export selected clients - group header
    $(document).on("click", '.grp_export', function() {
        var clients = new Array();
        var id = $('.selected-group').attr('gid');
        $("#datatable-" +  id).find(".ui-selectable tr a").each(function() {
            if($(this).parents(".ui-selectee").hasClass("ui-selected")) {
                clients.push($(this).attr("id"));
            }
        });

        $.ajax({
            url: "<%= groups_export_form_path %>",
            dataType : "script",
            cache: true,
            method: "post",
            data: {
                clients: clients
            }
        });

        $(this).blur();
    });

    // mark all clients in group - group header
    $(document).on("click", '.grp_mark_all', function() {
        var id = $('.selected-group').attr('gid');
        $("#datatable-" +  id).find(".ui-selectable tr a").each(function() {
            $(this).parents(".ui-selectee").addClass("ui-selected");
        });
        $(this).blur();
    });

    // unmark all clients in group - group header
    $(document).on("click", '.grp_unmark_all', function() {
        var id = $('.selected-group').attr('gid');
        $("#datatable-" +  id).find(".ui-selectable tr a").each(function() {
            $(this).parents(".ui-selectee").removeClass("ui-selected");
        });
        $(this).blur();
    });

    // search -> button float & header
    $(".search_float, .search_header").click(function () {
        $("#wide-modal").modal('open');
        $.ajax({
        url: "<%= global_search_view_path %>",
            dataType : "script",
            cache: true
        });
    });

    // new group add -> button float
    $(".group_add_float").click(function () {
        $.ajax({
            url: "<%= new_group_path %>",
            dataType : "script",
            cache: true
        });
    });
</script>