config/routes.rb
require 'sidekiq/web'
Sidekiq::Web.set :session_secret, Rails.application.credentials[:secret_key_base]

Rails.application.routes.draw do
  resources :notes
  resources :issue_groups
  resources :issues
  resources :screenshots, only: [:edit, :update, :destroy]
  resources :reports
  resources :clients
  resources :issue_templates
  devise_for :users, controllers: { registrations: "registrations", sessions: "sessions"}
  mount ActionCable.server => '/cable'
  root to: redirect(path: '/scans')

  get '/scans' => 'pages#scans'

  get '/issue_templates/create_from_issue/:issue_id' => 'issue_templates#create_from_issue', as: :issue_template_create_from_issue
  post '/issue_templates/search' => 'issue_templates#search', as: :issue_templates_search
  post '/issue_templates/search_add' => 'issue_templates#search_add', as: :issue_templates_search_add

  post '/reports/change_parent' => 'reports#change_parent', as: :change_parent
  match '/reports/:id/export_docx' => 'reports#export_docx', as: :export_odt, via: [:get, :post]
  match '/reports/:id/export_xlsx' => 'reports#export_xlsx', as: :export_xlsx, via: [:get, :post]
  match '/reports/:id/export_verinice' => 'reports#export_verinice', as: :export_verinice, via: [:get, :post]

  # index ever used, ever?
  resources :groups, only: %i[create new]

  post 'groups/group' => 'groups#group', as: :single_group_html

  post 'groups/create_form' => 'groups#create_form'

  post 'groups/copy_form' => 'groups#copy_form'
  post 'groups/copy' => 'groups#copy'

  post 'groups/move_form' => 'groups#move_form'
  post 'groups/move' => 'groups#move'

  post 'groups/export_form' => 'groups#export_form'
  post 'groups/export' => 'groups#export'

  post 'groups/delete_form' => 'groups#delete_form'
  post 'groups/delete' => 'groups#delete'

  post 'groups/delete_clients_form' => 'groups#delete_clients_form'
  post 'groups/delete_clients' => 'groups#delete_clients'

  post 'groups/scan_form' => 'groups#scan_form'

  get 'groups/refresh' => 'groups#refresh', as: :group_refresh
  get 'groups/group_list' => 'groups#group_list', as: :group_list

  get '/issues/:id/update_template' => 'issues#update_template', as: :update_template
  get '/issues/:id/new_template' => 'issues#new_template', as: :new_template
  get '/issues/:id/confirm_update_template' => 'issues#confirm_update_template', as: :confirm_update_template
  get '/issues/:id/confirm_create_template' => 'issues#confirm_create_template', as: :confirm_create_template

  get '/groups' => 'groups#index'
  get '/pages/settings' => 'pages#settings', as: :global_settings

  get '/images' => 'images#index', as: :images
  get '/images/scan_all' => 'images#scan_all', as: :images_scan_all
  get '/images/scan_all_overwrite' => 'images#scan_all_overwrite', as: :images_scan_all_overwrite

  get '/clients/search/form' => 'clients#search_form', as: :global_search_view
  post '/clients/global_search' => 'clients#global_search', as: :global_search
  post '/clients/archive' => 'clients#archive', as: :clients_archive
  post '/clients/unarchive' => 'clients#unarchive', as: :clients_unarchive
  get '/clients/:id/new_issue_form' => 'clients#new_issue_form', as: :clients_new_issue_form
  get '/clients/:id/link_issue_form' => 'clients#link_issue_form', as: :clients_link_issue_form
  get '/clients/:id/link_issue/:issue' => 'clients#link_issue', as: :clients_link_issue
  get '/clients/:id/unlink_issue/:issue' => 'clients#unlink_issue', as: :clients_unlink_issue

  post 'setting/update_user_settings' => 'setting#update_user_settings', as: :update_user_settings
  post 'settings/update' => 'settings#update', as: :update_settings

  post 'scans/create' => 'scans#create'
  post 'scans/upload' => 'scans#upload'
  post 'scans/download' => 'scans#download', as: :download_scan
  authenticate :user do
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/models/report.rb
class Report < ApplicationRecord
  has_many :report_parts, as: :reportable

  def all_issues
    issue_array = []
    report_parts.each do |pt|
      pt.child_issues.each do |child|
        issue_array << child if child.type == 'Issue'
      end
    end
    issue_array
  end

  def self.prepare_text_docx(text) 
    text.gsub('<pre>', '<p>').gsub('</pre>', '</p>') if text
  end
end

app/controllers/reports_controller.rb
require 'sablon'
require 'axlsx'
class ReportsController < ApplicationController
  before_action :set_report, only: %i[show edit update destroy export_docx export_xlsx export_verinice]

  # GET /reports
  # GET /reports.json
  def change_parent
    source_param = params[:source]
    new_parent_param = params[:new_parent]
    if source_param.to_i == new_parent_param.to_i
      respond_with_notify('Source and parent are identical.', 'alert')
      return
    end

    if ReportPart.exists? source_param
      if ReportPart.exists? new_parent_param
        source = ReportPart.find(source_param)
        new_parent = ReportPart.find(new_parent_param)
        new_parent.report_parts << source
      else
        # IF parent not exists, source moved directly to report
        new_parent = Report.first_or_create
        new_parent.report_parts << ReportPart.find(source_param)
      end
      respond_with_refresh('Parent was successfully changed.', 'success')
    else
      respond_with_notify('Source not exists as report part.', 'alert')
      nil
    end
  end

  def index
    @current_report = Report.first_or_create
    @report_parts = @current_report.report_parts
  end

  # GET /reports/1
  # GET /reports/1.json
  def show; end

  # GET /reports/1/edit
  def edit; end

  # PATCH/PUT /reports/1
  # PATCH/PUT /reports/1.json
  def update
    return unless @report.update(report_params)

    respond_with_notify('Report was successfully updated.', 'success')
    nil
  end

  # DELETE /reports/1
  # DELETE /reports/1.json
  def destroy
    @report.destroy
    respond_to do |format|
      format.html { redirect_to reports_url, notice: 'Report was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # GET|POST /reports/1/export_docx
  def export_docx
    # init template files
    template_path = Rails.root.join('report-templates')
    FileUtils.mkdir_p(template_path)
    report_file_name = "Report Pentest - #{@report.title} #{Date.today.year}"
    output_file = File.new(Rails.root.join('tmp') + "#{report_file_name}.docx", 'w')

    Sablon.configure do |config|
      config.register_html_tag(:code, :inline,
                               properties: { rFonts: { ascii: 'Roboto Mono', cs: 'Roboto Mono' } })
    end
    template = Sablon.template(File.expand_path(Rails.root.join(template_path, 'envizon_template.docx')))

    # init strukts
    s_report = Struct.new(:item, :summary, :conclusion, :issue_groups)
    s_issue_group = Struct.new(:item, :index, :issues)
    s_issue = Struct.new(:item, :index, :targets, :description, :rating, :recommendation, :screenshots)
    s_image = Struct.new(:item, :index, :description, :pix)
    # Sablon.content(:image, string_io_obj)
    # init template context
    context = {
      title: report_file_name,
      report: s_report.new(
        @report, # report.summary
        Sablon.content(:html, <<-HTML.strip
        #{Report.prepare_text_docx(@report.summary)}
        HTML
        ), # report.conclusion
        Sablon.content(:html, <<-HTML.strip
        #{Report.prepare_text_docx(@report.conclusion)}
        HTML
        ), # report.issue_groups->issues->description
        @report.report_parts.order(:index).select { |rp| rp.is_a? IssueGroup }.each_with_index.map do |ig, index_ig| # report.issue_groups
          s_issue_group.new(
            ig, # report.issue_groups->item
            index_ig, # report.issue_groups->index
            ig.ordered_child_issues.each_with_index.map do |issue, index_issue| # report.issue_groups->issues
              s_issue.new(
                issue, # report.issue_groups->issues->item
                index_issue, # report.issue_groups->issues->index
                (issue.clients.map { |c| c.ip.to_s + (c.hostname.present? ? " (#{c.hostname})" : '') } + (issue.customtargets.present? ? issue.customtargets.lines : [])).map(&:strip).reject(&:empty?), # report.issue_groups->issues->targets
                Sablon.content(:html, <<-HTML.strip
                #{Report.prepare_text_docx(issue.description)}
                HTML
                ), # report.issue_groups->issues->description
                Sablon.content(:html, <<-HTML.strip
                #{Report.prepare_text_docx(issue.rating)}
                HTML
                ), # report.issue_groups->issues->rating
                Sablon.content(:html, <<-HTML.strip
                #{Report.prepare_text_docx(issue.recommendation)}
                HTML
                ), # report.issue_groups->issues->recommendation
                issue.screenshots.each_with_index.map do |screenshot, index_screenshot|
                  s_image.new( # report.issue_groups->issues->screenshots
                    screenshot, # report.issue_groups->issues->screenshots->item
                    index_screenshot, # report.issue_groups->issues->screenshots->index
                    screenshot.description, # report.issue_groups->issues->screenshots->description
                    # Sablon.content(:image, '/usr/src/app/envizon/report-templates/test.png', properties: {height: '2cm', width: '2cm'})  #report.issue_groups->issues->screenshots->content
                    Sablon.content(:image, StringIO.new(IO.binread(ActiveStorage::Blob.service.send(:path_for, screenshot.image.key))), filename: 'test.png', properties: { height: "#{screenshot.size_relation * 16.08}cm", width: '16.08cm' }) # report.issue_groups->issues->screenshots->content
                    # use params like:
                    # Sablon.content(:image, 'path', filename: 'test.png', properties: {height: '2cm', width: '2cm'})
                  )
                end
              )
            end
          )
        end
      )
    }

    # generate docx and let them download
    template.render_to_file output_file, context
    send_file output_file, filename: "#{report_file_name}.docx", type: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document'
    nil
  end

  def export_xlsx
    #https://github.com/randym/axlsx
    #https://github.com/randym/axlsx/blob/master/examples/example.rb

    report_file_name = "Report Pentest Table - #{@report.title} #{Date.today.year}"
    output_file = File.new(Rails.root.join('tmp') + "#{report_file_name}.xls", 'w')

    package = Axlsx::Package.new
    workbook = package.workbook

    workbook.styles do |s|
      #head = s.add_style :bg_color => "00", :fg_color => "FF", :b => true  
      head = s.add_style :b => true  
      severity =[
        (s.add_style :fg_color => "3fb079"),
        (s.add_style :fg_color => "0b5394"),
        (s.add_style :fg_color => "b45f06"),
        (s.add_style :fg_color => "990000"),
        (s.add_style :fg_color => "9900ff"),
        (s.add_style :fg_color => "999999")
      ]

      workbook.add_worksheet(:name => "Pentest Report") do |sheet|
        sheet.add_row ["Title", "Severity", "Description", "Targets", "Rating", "Recommendation"], :style => head

        @report.report_parts.order(:index).select { |rp| rp.is_a? IssueGroup }.each_with_index.map do |ig, index_ig| # report.issue_groups
          ig.ordered_child_issues.each_with_index.map do |issue, index_issue| # report.issue_groups->issues
            begin
              sev_cell = severity[issue.severity]
            rescue => exception
              sev_cell = severity.last
            end

            case issue.severity
            when 0
              severity_text = 'information'
            when 1
              severity_text = 'low'
            when 2
              severity_text = 'medium'
            when 3
              severity_text = 'high'
            when 4
              severity_text = 'critical'
            else
              severity_text = 'unknown'
            end
            
            sheet.add_row [
                Nokogiri::HTML(issue.title).text,
                severity_text,
                Nokogiri::HTML(issue.description).text,
                (issue.clients.map { |c| c.ip.to_s + (c.hostname.present? ? " (#{c.hostname})" : '') } + (issue.customtargets.present? ? issue.customtargets.lines : [])).map(&:strip).reject(&:empty?).join(" \n"), # report.issue_groups->issues->targets
                Nokogiri::HTML(issue.rating).text,
                Nokogiri::HTML(issue.recommendation).text
              ], :style => [nil, sev_cell, nil, nil, nil, nil]
          end
        end
      end
    end

    File.delete(output_file) if File.exist?(output_file)
    package.serialize(output_file)

    send_file output_file, filename: "#{report_file_name}.xlsx", type: 'application/xml'
    nil
  end

  def export_verinice
    report_file_name = "Verinice Report Pentest - #{@report.title} #{Date.today.year}"
    output_file = File.new(Rails.root.join('tmp') + "#{report_file_name}.xml", 'w')

    @verinice_ids = []
    @rand = Random.new
    template_path = Rails.root.join('report-templates', 'evait_verinice.xml.erb')

    issues = @report.all_issues

    targets_ids = {}
    issue_ids = {}
    issues_to_targets = {}

    issues.each do |issue|
      en_issue = verinice_entity
      issue_ids[issue.id] = en_issue
      issues_to_targets[en_issue] = []
      # map linked clients
      issue.clients.each do |clients|
        en_clients = verinice_entity
        targets_ids[clients.id] = en_clients
        issues_to_targets[en_issue] << en_clients
      end
      # map custom targets
      issue.customtargets.lines.each do |c_targets|
        en_clients = verinice_entity
        targets_ids[c_targets] = en_clients
        issues_to_targets[en_issue] << en_clients
      end
    end

    # issue.clients.map{|c| c.ip.to_s + (c.hostname.present? ? " (#{c.hostname})" : '')} + (issue.customtargets.present? ? issue.customtargets.lines : [])

    erb = ERB.new(File.read(template_path), nil, '<>-')
    res = erb.result(binding)
    # remove empty lines:
    res = res.lines.reject { |s| s.strip.empty? }.join

    # replace unicode-chars which verinice doesn't like

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/reports/_edit.html.erb
<div class="container pt-2">
    <%= simple_form_for @report, remote: true do |f| %>
        <div class="row">
            <%= f.input :title, wrapper_html: { class: 'col s4' } %>
            <%= f.input :logo_url, wrapper_html: { class: 'col s4' } %>
            <%= f.input :contact_person, wrapper_html: { class: 'col s4' } %>
        </div>
        <div class="row">
            <%= f.input :company_name, wrapper_html: { class: 'col s3' } %>
            <%= f.input :street, wrapper_html: { class: 'col s3' } %>
            <%= f.input :postalcode, wrapper_html: { class: 'col s3' } %>
            <%= f.input :city, wrapper_html: { class: 'col s3' } %>
        </div>
        <div class="row">
            <%= f.input :summary, wrapper_html: { class: 'col s12' }, input_html: { class: 'report-editor'} %>
        </div>
        <div class="row">
            <div class="col s12 input-field">
                <button type="submit" class="btn right blue darken-2">Update <i class="left material-icons">cached</i></button>
            </div>  
        </div>
    <% end %>
</div>

app/views/reports/edit.js.erb
$("#medium-modal-content").html("<%= j render(partial: 'reports/edit') %>");
$(".report-editor").each(function(index, value) {
    ClassicEditor
    .create( value, {
        toolbar: {
            items: [
                'bold',
                'italic',
                'fontColor',
                'fontBackgroundColor',
                'codeBlock',
                'highlight',
                'fontFamily',
                'horizontalLine',
                'specialCharacters',
                'link',
                'undo',
                'redo'
            ]
        },
        language: 'de'				
    });
});
M.updateTextFields();
$("#medium-modal").modal('open');

app/views/reports/index.html.erb
<div class="reports-page">
  <% if @report_parts.empty? %>
    <div class="row">
      <div class="col s12">
        <%= link_to new_issue_group_path, remote: true do %>
          <div class="placeholder tooltipped modal-trigger center-align" data-position="top" data-tooltip="Add new issue group">
              <i class="material-icons blue-text text-lighten-4">add</i>
          </div>
        <% end %>  
      </div>
    </div>
  <% end %>
  <div class="row">
    <div class="col s3 reports-container pl-1">
      <div class="row">
        <div id="report_tree" class="col s12">
          <%= render partial: "report_parts/report_tree" %>
        </div>
      </div>
    </div>
    <div class="col s9 offset-s3 editor-container"><!-- scrollbar -->
      <!-- partial render issue (selected) siehe -> issue template -->
      <!-- partial render report edit -->
    </div>
  </div>
</div>

<!-- Modal (medium) -->
<div id="medium-modal" class="modal modal-fixed-footer">
  <div id="medium-modal-content">
  </div>
</div>

<% case current_user.settings.where(name: 'report_mode').first_or_create.value %>
<% when "presentation" %>
  <div class="fixed-action-btn">
    <%= simple_form_for :settings, url: update_settings_path do |f| %>
      <input type="hidden" value="edit" name="report_mode"/>
      <button class="btn-floating btn-large green darken-2 submit tooltipped" data-position="left" data-tooltip="Disable presentation mode"><i class="material-icons">stop_screen_share</i></button>
    <% end %>
  </div>
<% else %>
  <div class="fixed-action-btn toolbar direction-top no-autoinit">
    <a class="btn-floating btn-large blue darken-3"><i class="large material-icons">mode_edit</i></a>
    <ul>
      <li>
        <%= link_to new_issue_path, remote: true, class: "tooltipped", data: { position: "top", tooltip: "Add new issue"} do %><i class="material-icons">add</i><% end %>
      </li>
      <li>
        <%= link_to export_odt_path(@current_report), class: "tooltipped", data: { position: "top", tooltip: "Export current report as docx"} do %><i class="material-icons">post_add</i><% end %>
      </li>
      <li>
        <%= link_to export_xlsx_path(@current_report), class: "tooltipped", data: { position: "top", tooltip: "Export current report as xlsx"} do %><i class="material-icons">table_chart</i><% end %>
      </li>
      <li>
        <%= link_to new_issue_group_path, remote: true, class: "tooltipped", data: { position: "top", tooltip: "Add new issue group"} do %><i class="material-icons">playlist_add</i><% end %>
      </li>
      <li class="waves-effect waves-light">
        <%= link_to edit_report_path(@current_report), remote: true, class: "tooltipped", data: { position: "top", tooltip: "Edit current report"} do %><i class="material-icons">edit</i><% end %>
      </li>
      <li>
        <%= simple_form_for :settings, url: update_settings_path do |f| %>
          <input type="hidden" value="presentation" name="report_mode"/>
          <a href="#" onclick='$(this).parent().submit();' class="submit tooltipped" data-position="top" data-tooltip="Enable presentation mode"><i class="material-icons">screen_share</i></a>
        <% end %>
      </li>
    </ul>
  </div>
<% end %>

<script>
  var pasteTarget = document.getElementsByTagName("body");
  pasteTarget[0].addEventListener("paste", uploadClipboardData);
  function uploadClipboardData(e){
      for (var i = 0 ; i < e.clipboardData.items.length ; i++) {
          var item = e.clipboardData.items[i];
          if (item.type.indexOf("image") != -1) {
              var fileInput = document.getElementById("issue_screenshot_image");
              fileInput.files = e.clipboardData.files;
              $("#issue_screenshot_image_path").val("Image from clipboard ...");
          };
      };
  };
  $(document).ready(function(){
    $('.tap-target').tapTarget('open');
  });
  $(window).bind('keydown', function(event) {
    if (event.ctrlKey || event.metaKey) {
      switch (String.fromCharCode(event.which).toLowerCase()) {
      case 's':
          event.preventDefault();
          $(".btn-save").trigger("click");
          break;
      }
    }
  });
</script>